/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright 1997-2002, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Single_crystal_sqw
*
* %I
* Written by: Kristian Nielsen
* Date: December 1999
* Version: $Revision$
* Origin: Risoe
* Release: McStas 1.6
* Modified by: EF, 22nd Apr 2003 : now uses Read_Table library
* Modified by: M. Schulz, March 2012 : allow to curve the crystal planes
* Modified by: EF, PW, May 2014: code efficiency improvement when SPLIT is used
* Modified by: EF, PW, 2015: powder/PG and texture mode
*
* Mosaic single crystal with multiple scattering vectors, optimised for speed
* with large crystals and many reflections.
*
* %D
* Single crystal with mosaic. Delta-D/D option for finite-size effects.
* Rectangular geometry. Multiple scattering and secondary extinction included.
* The mosaic may EITHER be specified isotropic by setting the mosaic input
* parameter, OR anisotropic by setting the mosaic_a, mosaic_b, and mosaic_c
* parameters.
* The crystal lattice can be bent locally, keeping the external geometry unchanged.
* Curvature is spherical along vertical and horizontal axes.
*
* In order to dramatically improve the simulation efficiency, we recommend to
* use a SPLIT keyword on this component (or prior to it), as well as to disable
* the multiple scattering handling by setting order=1. This is especially powerfull
* for large reflection lists such as with macromolecular proteins.
*
* <b>Sample shape:</b>
* Sample shape may be a cylinder, a sphere, a box or any other shape
*   box/plate:       xwidth x yheight x zdepth
*   cylinder:        radius x yheight
*   sphere:          radius (yheight=0)
*   any shape:       geometry=OFF file
*
*   The complex geometry option handles any closed non-convex polyhedra.
*   It computes the intersection points of the neutron ray with the object  
*   transparently, so that it can be used like a regular sample object.
*   It supports the PLY, OFF and NOFF file format but not COFF (colored faces). 
*   Such files may be generated from XYZ data using:
*     qhull < coordinates.xyz Qx Qv Tv o > geomview.off 
*   or
*     powercrust coordinates.xyz
*   and viewed with geomview or java -jar jroff.jar (see below).
*   The default size of the object depends on the OFF file data, but its 
*   bounding box may be resized using xwidth,yheight and zdepth.
*
* <b>Crystal definition file format</b>
* Crystal structure is specified with an ascii data file. Each line contains
* 4 or more numbers, separated by white spaces:
*
*       h k l ... F2
*
* The first three numbers are the (h,k,l) indices of the reciprocal lattice
* point, and the 7-th number is the value of the structure factor |F|**2, in
* barns. The rest of the numbers are not used; the file is in the format
* output by the Crystallographica program.
* The reflection list should be ordered by decreasing d-spacing values.
* Lines begining by '#' are read as comments (ignored). Most sample parameters
* may be defined from the data file header, following the same mechanism as
* PowderN.
*
* Current data file header keywords include, for data format specification:
*    #column_h <index of the Bragg Qh column>
*    #column_k <index of the Bragg Qk column>
*    #column_l <index of the Bragg Ql column>
*    #column_F2 <index of the squared str. factor '|F|^2' column [b]>
*    #column_F  <index of the structure factor norm '|F|' column>
* and for material specification:
*    #sigma_abs <value of absorption cross section [barns]>
*    #sigma_inc <value of incoherent cross section [barns]>
*    #Delta_d/d <value of Detla_d/d width for all lines>
*    #lattice_a <value of the a lattice parameter [Angs]>
*    #lattice_b <value of the b lattice parameter [Angs]>
*    #lattice_c <value of the c lattice parameter [Angs]>
*    #lattice_aa <value of the alpha lattice angle [deg]>
*    #lattice_bb <value of the beta  lattice angle [deg]>
*    #lattice_cc <value of the gamma lattice angle [deg]>
*
* See the Component Manual for more defails.
*
* Example: Single_crystal(xwidth=0.01, yheight=0.01, zdepth=0.01,
*           mosaic = 5, reflections="YBaCuO.lau")
*
* A PG graphite crystal plate, cut for (002) reflections
*   Single_crystal(xwidth = 0.002, yheight = 0.1, zdepth = 0.1, 
*     mosaic = 30, reflections = "C_graphite.lau", 
*     ax=0,      ay=2.14,   az=-1.24,
*     bx = 0,    by = 0,    bz =  2.47,
*     cx = 6.71, cy = 0,    cz =  0)
*
* A leucine protein, without multiple scattering
*   Single_crystal(xwidth=0.005, yheight=0.005, zdepth=0.005,
*     mosaic = 5, reflections="leucine.lau", order=1)
*
* A Vanadium incoherent elastic scattering with multiple scattering
*   Single_crystal(xwidth=0.01, yheight=0.01, zdepth=0.01,
*           reflections="", sigma_abs=5.08, sigma_inc=4.935,
*           ax=3.0282, by=3.0282, cz=3.0282/2)
*
* Also, always use a non-zero value of delta_d_d.
*
* %VALIDATION:
* This component has been validated.
*
* %P
* INPUT PARAMETERS:
* radius:    Outer radius of sample in (x,z) plane [m]
* xwidth:    Width of crystal [m]
* yheight:   Height of crystal [m]
* zdepth:    Depth of crystal (no extinction simulated) [m]
* geometry:  Name of an Object File Format (OFF) or PLY file for complex geometry. 
*              The OFF/PLY file may be generated from XYZ coordinates using qhull/powercrust [str]
* delta_d_d: Lattice spacing variance, gaussian RMS [1]
* mosaic:    Crystal mosaic (isotropic), gaussian RMS. Puts the crystal in the 
*              isotropic mosaic model state, thus disregarding other mosaicity parameters. [arc minutes]
* mosaic_a:  Horizontal (rotation around lattice vector a) mosaic (anisotropic), gaussian RMS. 
*              Put the crystal in the anisotropic crystal vector state. I.e. model mosaicity
*              through rotation around the crystal lattice vectors. Has precedence over
*              in-plane mosaic model. [arc minutes]
* mosaic_b:  Vertical (rotation around lattice vector b) mosaic (anisotropic), 
*              gaussian RMS. [arc minutes]
* mosaic_c:  Out-of-plane (Rotation around lattice vector c) mosaic (anisotropic), 
*              gaussian RMS [arc minutes]
* mosaic_AB: In Plane mosaic rotation and plane vectors (anisotropic), 
*              mosaic_A, mosaic_B, A_h,A_k,A_l, B_h,B_k,B_l. Puts the crystal in 
*              the in-plane mosaic state. Vectors A and B define plane in which 
*              the crystal roation is defined, and mosaic_A, mosaic_B, denotes the 
*              resp. mosaicities (gaussian RMS) with respect to the the two 
*              reflections chosen by A and B (Miller indices). [arc_minutes, arc_minutes,1, 1, 1, 1, 1, 1]
* 
* recip_cell: Choice of direct/reciprocal (0/1) unit cell definition [1]
* ax:        Coordinates of first (direct/recip) unit cell vector [AA or AA^-1]
* ay:        a on y axis
* az:        a on z axis
* bx:        Coordinates of second (direct/recip) unit cell vector [AA or AA^-1]
* by:        b on y axis
* bz:        b on z axis
* cx:        Coordinates of third (direct/recip) unit cell vector [AA or AA^-1]
* cy:        c on y axis
* cz:        c on z axis
* reflections: File name containing structure factors of reflections. Use
*              empty ("") or NULL for incoherent scattering only [string]
* order:     Limit multiple scattering up to given order
*              (0: all, 1: first, 2: second, ...) [1]
*
* Optional input parameters:
*
* p_transmit: Monte Carlo probability for neutrons to be transmitted
*               without any scattering. Used to improve statistics from
*               weak reflections [1]
* sigma_abs: Absorption cross-section per unit cell at 2200 m/s [barns]
* sigma_inc: Incoherent scattering cross-section per unit cell
*              Use -1 to unactivate [barns]
* aa:        Unit cell angles alpha, beta and gamma. Then uses norms of
*              vectors a,b and c as lattice parameters [deg]
* bb:        Beta angle [deg] 
* cc:        Gamma angle [deg].
* barns:     Flag to indicate if |F|^2 from 'reflections' is in barns or fm^2. 
*              barns=1 for laz and isotropic constant elastic scattering (reflections=NULL), 
*              barns=0 for lau type files [1]
* RX:        Radius of horizontal along X lattice curvature. flat for 0 (m)
* RY:        Radius of vertical lattice curvature. flat for 0 (m)
* RZ:        Radius of horizontal along Z lattice curvature. flat for 0 (m)
* powder:    Flag to indicate powder mode, for simulation of Debye-Scherrer cones
*              via random crystallite orientation. A powder texture can be 
*              approximated with 0<powder<1 (1)
* PG:        Flag to indicate "Pyrolytic Graphite" mode, only meaningful with 
*              choice of Graphite.lau, models PG crystal. A powder texture can be 
*              approximated with 0<PG<1 with main axis on 'c' (1)
*
* omega: Added in later by T. Halloran to define a particular energy transfer. This is used to 
*    simulate a delta function for resolution calclulations. 
* 
* OUTPUT PARAMETERS:
*
* hkl_info: Internal [structure]
* hkl_info.type: interaction type of event 't'=Transmit, 'i'=Incoherent, 'c'=Coherent [char]
* hkl_info.h:   
* hkl_info.k: wavevector indices of last coherent scattering event [Angs-1]
* hkl_info.l:
*
* %L
* See <a href="http://icsd.ill.fr">ICSD</a> Inorganic Crystal Structure Database
* %L
* <a href="http://www.ncnr.nist.gov/resources/n-lengths/">Cross sections for single elements</a> 
* %L
* <a href="http://www.ncnr.nist.gov/resources/sldcalc.html>Cross sections for compounds</a>
* %L
* <a href="http://www.webelements.com/">Web Elements</a>
* %L
* <a href="http://www.ill.eu/sites/fullprof/index.html">Fullprof</a> powder refinement
* %L
* <a href="http://www.crystallographica.com/">Crystallographica</a> software
* %L
* <a href="http://www.geomview.org">Geomview and Object File Format (OFF)</a>
* %L
* Java version of Geomview (display only) <a href="http://www.holmes3d.net/graphics/roffview/">jroff.jar</a>
* %L
* <a href="http://qhull.org">qhull</a>
* %L
* <a href="http://www.cs.ucdavis.edu/~amenta/powercrust.html">powercrust</a>
*
* %E
****************************************************************************/
