% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Jul-2023 14:59:44
%  MATLAB version: 9.14.0.2286388 (R2023a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('test.mat');

CrI3 = saveVarsMat.CrI3; % <1x1 spinw> unsupported class

FMchain = saveVarsMat.FMchain; % <1x1 spinw> unsupported class

FMpowspec = saveVarsMat.FMpowspec; % <1x1 struct> too many elements at FMpowspec.swConv

FMspec = saveVarsMat.FMspec; % <1x1 struct> too many elements at FMspec.Sab

ans = saveVarsMat.ans; % <1x1 table> unsupported class

clear saveVarsMat;
